[wallpapers]
path = "~/.config/hypr/images/"
interval = 10 # change every hour
extensions = ["jpg", "jpeg", "png"]
recurse = true
unique = true
# Using swww
command = "swww img --transition-type any --transition-fps 60 \"[file]\""
clear_command = "swww clear"
