import = ["/home/fixmin/.config/alacritty/themes/github_dark_high_contrast.toml"]

[colors]

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Underline"

[cursor.vi_mode_style]
blinking = "Always"
shape = "Underline"


[env]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 1
y = 2

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Super"

[window]
decorations = "None"
opacity = 0.6
blur = true
padding = { x = 20 , y = 20}
dynamic_padding = true

